#version: '3.8'  # Specify the version (recommended)

services:
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
      - mysql

  spring-petclinic:
    image: openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    volumes:
      - ./target/spring-petclinic-3.3.0-SNAPSHOT.jar:/app.jar  # Assuming your JAR file is built in the target directory
    command: ["java", "-jar", "/app.jar"]
    depends_on:
      - mysql

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
      - postgres
